server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Purna@123
    url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb
    username: PurnaChander
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:http://localhost:9296

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-56652480.okta.com/oauth2/default
          authorities-claim-name: groups
          authority-prefix: ROLE_



#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}